[package]
name = "pwcli"
description = "Pirewire CLI in rust"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29.0", features = ["user"] }
tokio = { version = "1.40.0", features = ["net", "rt"] }
